export const ADD_TODO = 'add_todo'
export const SET_TODO = 'set_todo'
export const DELETE_TODO = 'delete_todo'
export const UPDATE_TODO = 'update_todo'
export const UPDATE_NAME_TODO = 'update_name_todo'